source 'https://rubygems.org'

gem "middleman" 
gem "middleman-livereload"
gem "middleman-blog"
gem "middleman-blog-drafts"
gem "middleman-deploy"
gem "sanitize"
gem "kramdown"
gem "rack"
gem "rack-rewrite"
gem "rack-contrib"
gem "rack-robotz"
gem "puma"
gem "rake"
